### PR TITLE
Fix initializing child nodes when raise_unknown_elements is false

### LINKED ISSUE #22: Fails to initialize child nodes when unknown attribute encountered (with `raise_unknown_elements = false`)
STR:
1. Set `CXML.raise_unknown_elements = false`
2. Create a cxml document with an invalid attribute and child node(s) (see example below)
3. Parse with `CXML::Document.new.from_xml(decoded_cxml)`

O:
The unknown attribute correctly causes a warning instead of an error but all child nodes are not initialized.

D:
Warn about unknown attributes on the node and initialize all child nodes.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cXML SYSTEM "http://xml.cXML.org/schemas/cXML/1.2.020/cXML.dtd">
<cXML xml:lang="en-US" payloadID="test-id" timestamp="2020-09-10T20:32:26+00:00">
  <Response invalid="invalid">
    <Status code="200" text="Ok">123456</Status>
  </Response>
</cXML>
```

### PR DESCRIPTION
**Pull request by tyleralves**
Fixes #22 

This commit fixes a bug where child nodes are not initialized for a
node that has an unknown attribute, and raise_unknown_elements is false.

### CODE REVIEW

File: lib/cxml/document_node.rb [hunk 1]
```diff
@@ -136,6 +134,8 @@ def initialize_attribute_raw(key, val)
       else
         send("#{key}=", val)
       end
+    rescue NoMethodError => e
```
Comment (tyleralves) [inline lib/cxml/document_node.rb:137]: Previously an unknown attribute exception here would be caught in the parent node's `rescue NoMethodError => e`. This would break out of recursing through child nodes for the node with the invalid attribute.

**Review by joshbeckman — APPROVED** [review]
Thanks for improving this!

**Comment by joshbeckman** [comment]
Published in v0.8.0
